// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// ConfirmAppointmentForPatientOKCode is the HTTP code returned for type ConfirmAppointmentForPatientOK
const ConfirmAppointmentForPatientOKCode int = 200

/*ConfirmAppointmentForPatientOK appoint for a patient

swagger:response confirmAppointmentForPatientOK
*/
type ConfirmAppointmentForPatientOK struct {
}

// NewConfirmAppointmentForPatientOK creates ConfirmAppointmentForPatientOK with default headers values
func NewConfirmAppointmentForPatientOK() *ConfirmAppointmentForPatientOK {

	return &ConfirmAppointmentForPatientOK{}
}

// WriteResponse to the client
func (o *ConfirmAppointmentForPatientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ConfirmAppointmentForPatientInternalServerErrorCode is the HTTP code returned for type ConfirmAppointmentForPatientInternalServerError
const ConfirmAppointmentForPatientInternalServerErrorCode int = 500

/*ConfirmAppointmentForPatientInternalServerError internal server error

swagger:response confirmAppointmentForPatientInternalServerError
*/
type ConfirmAppointmentForPatientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewConfirmAppointmentForPatientInternalServerError creates ConfirmAppointmentForPatientInternalServerError with default headers values
func NewConfirmAppointmentForPatientInternalServerError() *ConfirmAppointmentForPatientInternalServerError {

	return &ConfirmAppointmentForPatientInternalServerError{}
}

// WithPayload adds the payload to the confirm appointment for patient internal server error response
func (o *ConfirmAppointmentForPatientInternalServerError) WithPayload(payload *models.Error) *ConfirmAppointmentForPatientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the confirm appointment for patient internal server error response
func (o *ConfirmAppointmentForPatientInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfirmAppointmentForPatientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
