// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// GetAppointmentsByPatientOKCode is the HTTP code returned for type GetAppointmentsByPatientOK
const GetAppointmentsByPatientOKCode int = 200

/*GetAppointmentsByPatientOK appoints for a patient

swagger:response getAppointmentsByPatientOK
*/
type GetAppointmentsByPatientOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Appointment `json:"body,omitempty"`
}

// NewGetAppointmentsByPatientOK creates GetAppointmentsByPatientOK with default headers values
func NewGetAppointmentsByPatientOK() *GetAppointmentsByPatientOK {

	return &GetAppointmentsByPatientOK{}
}

// WithPayload adds the payload to the get appointments by patient o k response
func (o *GetAppointmentsByPatientOK) WithPayload(payload []*models.Appointment) *GetAppointmentsByPatientOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get appointments by patient o k response
func (o *GetAppointmentsByPatientOK) SetPayload(payload []*models.Appointment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppointmentsByPatientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Appointment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAppointmentsByPatientInternalServerErrorCode is the HTTP code returned for type GetAppointmentsByPatientInternalServerError
const GetAppointmentsByPatientInternalServerErrorCode int = 500

/*GetAppointmentsByPatientInternalServerError internal server error

swagger:response getAppointmentsByPatientInternalServerError
*/
type GetAppointmentsByPatientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAppointmentsByPatientInternalServerError creates GetAppointmentsByPatientInternalServerError with default headers values
func NewGetAppointmentsByPatientInternalServerError() *GetAppointmentsByPatientInternalServerError {

	return &GetAppointmentsByPatientInternalServerError{}
}

// WithPayload adds the payload to the get appointments by patient internal server error response
func (o *GetAppointmentsByPatientInternalServerError) WithPayload(payload *models.Error) *GetAppointmentsByPatientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get appointments by patient internal server error response
func (o *GetAppointmentsByPatientInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppointmentsByPatientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
