// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// GetPatientbyIDOKCode is the HTTP code returned for type GetPatientbyIDOK
const GetPatientbyIDOKCode int = 200

/*GetPatientbyIDOK result get patient

swagger:response getPatientbyIdOK
*/
type GetPatientbyIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Patient `json:"body,omitempty"`
}

// NewGetPatientbyIDOK creates GetPatientbyIDOK with default headers values
func NewGetPatientbyIDOK() *GetPatientbyIDOK {

	return &GetPatientbyIDOK{}
}

// WithPayload adds the payload to the get patientby Id o k response
func (o *GetPatientbyIDOK) WithPayload(payload *models.Patient) *GetPatientbyIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get patientby Id o k response
func (o *GetPatientbyIDOK) SetPayload(payload *models.Patient) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPatientbyIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPatientbyIDInternalServerErrorCode is the HTTP code returned for type GetPatientbyIDInternalServerError
const GetPatientbyIDInternalServerErrorCode int = 500

/*GetPatientbyIDInternalServerError internal server error

swagger:response getPatientbyIdInternalServerError
*/
type GetPatientbyIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPatientbyIDInternalServerError creates GetPatientbyIDInternalServerError with default headers values
func NewGetPatientbyIDInternalServerError() *GetPatientbyIDInternalServerError {

	return &GetPatientbyIDInternalServerError{}
}

// WithPayload adds the payload to the get patientby Id internal server error response
func (o *GetPatientbyIDInternalServerError) WithPayload(payload *models.Error) *GetPatientbyIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get patientby Id internal server error response
func (o *GetPatientbyIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPatientbyIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
