// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAppointmentsByPatientHandlerFunc turns a function with the right signature into a get appointments by patient handler
type GetAppointmentsByPatientHandlerFunc func(GetAppointmentsByPatientParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppointmentsByPatientHandlerFunc) Handle(params GetAppointmentsByPatientParams) middleware.Responder {
	return fn(params)
}

// GetAppointmentsByPatientHandler interface for that can handle valid get appointments by patient params
type GetAppointmentsByPatientHandler interface {
	Handle(GetAppointmentsByPatientParams) middleware.Responder
}

// NewGetAppointmentsByPatient creates a new http.Handler for the get appointments by patient operation
func NewGetAppointmentsByPatient(ctx *middleware.Context, handler GetAppointmentsByPatientHandler) *GetAppointmentsByPatient {
	return &GetAppointmentsByPatient{Context: ctx, Handler: handler}
}

/*GetAppointmentsByPatient swagger:route GET /v1/patients/{id}/appointments patients getAppointmentsByPatient

GetAppointmentsByPatient get appointments by patient API

*/
type GetAppointmentsByPatient struct {
	Context *middleware.Context
	Handler GetAppointmentsByPatientHandler
}

func (o *GetAppointmentsByPatient) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAppointmentsByPatientParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
