// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// RequestAppointmentForPatientOKCode is the HTTP code returned for type RequestAppointmentForPatientOK
const RequestAppointmentForPatientOKCode int = 200

/*RequestAppointmentForPatientOK appoint for a patient

swagger:response requestAppointmentForPatientOK
*/
type RequestAppointmentForPatientOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Appointment `json:"body,omitempty"`
}

// NewRequestAppointmentForPatientOK creates RequestAppointmentForPatientOK with default headers values
func NewRequestAppointmentForPatientOK() *RequestAppointmentForPatientOK {

	return &RequestAppointmentForPatientOK{}
}

// WithPayload adds the payload to the request appointment for patient o k response
func (o *RequestAppointmentForPatientOK) WithPayload(payload []*models.Appointment) *RequestAppointmentForPatientOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request appointment for patient o k response
func (o *RequestAppointmentForPatientOK) SetPayload(payload []*models.Appointment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestAppointmentForPatientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Appointment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// RequestAppointmentForPatientInternalServerErrorCode is the HTTP code returned for type RequestAppointmentForPatientInternalServerError
const RequestAppointmentForPatientInternalServerErrorCode int = 500

/*RequestAppointmentForPatientInternalServerError internal server error

swagger:response requestAppointmentForPatientInternalServerError
*/
type RequestAppointmentForPatientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRequestAppointmentForPatientInternalServerError creates RequestAppointmentForPatientInternalServerError with default headers values
func NewRequestAppointmentForPatientInternalServerError() *RequestAppointmentForPatientInternalServerError {

	return &RequestAppointmentForPatientInternalServerError{}
}

// WithPayload adds the payload to the request appointment for patient internal server error response
func (o *RequestAppointmentForPatientInternalServerError) WithPayload(payload *models.Error) *RequestAppointmentForPatientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request appointment for patient internal server error response
func (o *RequestAppointmentForPatientInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestAppointmentForPatientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
