// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// RequestAppointmentForPatientOKCode is the HTTP code returned for type RequestAppointmentForPatientOK
const RequestAppointmentForPatientOKCode int = 200

/*RequestAppointmentForPatientOK appoint for a patient

swagger:response requestAppointmentForPatientOK
*/
type RequestAppointmentForPatientOK struct {
}

// NewRequestAppointmentForPatientOK creates RequestAppointmentForPatientOK with default headers values
func NewRequestAppointmentForPatientOK() *RequestAppointmentForPatientOK {

	return &RequestAppointmentForPatientOK{}
}

// WriteResponse to the client
func (o *RequestAppointmentForPatientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RequestAppointmentForPatientForbiddenCode is the HTTP code returned for type RequestAppointmentForPatientForbidden
const RequestAppointmentForPatientForbiddenCode int = 403

/*RequestAppointmentForPatientForbidden internal server error

swagger:response requestAppointmentForPatientForbidden
*/
type RequestAppointmentForPatientForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRequestAppointmentForPatientForbidden creates RequestAppointmentForPatientForbidden with default headers values
func NewRequestAppointmentForPatientForbidden() *RequestAppointmentForPatientForbidden {

	return &RequestAppointmentForPatientForbidden{}
}

// WithPayload adds the payload to the request appointment for patient forbidden response
func (o *RequestAppointmentForPatientForbidden) WithPayload(payload *models.Error) *RequestAppointmentForPatientForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request appointment for patient forbidden response
func (o *RequestAppointmentForPatientForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestAppointmentForPatientForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RequestAppointmentForPatientInternalServerErrorCode is the HTTP code returned for type RequestAppointmentForPatientInternalServerError
const RequestAppointmentForPatientInternalServerErrorCode int = 500

/*RequestAppointmentForPatientInternalServerError internal server error

swagger:response requestAppointmentForPatientInternalServerError
*/
type RequestAppointmentForPatientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRequestAppointmentForPatientInternalServerError creates RequestAppointmentForPatientInternalServerError with default headers values
func NewRequestAppointmentForPatientInternalServerError() *RequestAppointmentForPatientInternalServerError {

	return &RequestAppointmentForPatientInternalServerError{}
}

// WithPayload adds the payload to the request appointment for patient internal server error response
func (o *RequestAppointmentForPatientInternalServerError) WithPayload(payload *models.Error) *RequestAppointmentForPatientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request appointment for patient internal server error response
func (o *RequestAppointmentForPatientInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestAppointmentForPatientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
