// Code generated by go-swagger; DO NOT EDIT.

package professionals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// AttendAppointmentProfessionalOKCode is the HTTP code returned for type AttendAppointmentProfessionalOK
const AttendAppointmentProfessionalOKCode int = 200

/*AttendAppointmentProfessionalOK set attend appointment for professional

swagger:response attendAppointmentProfessionalOK
*/
type AttendAppointmentProfessionalOK struct {
}

// NewAttendAppointmentProfessionalOK creates AttendAppointmentProfessionalOK with default headers values
func NewAttendAppointmentProfessionalOK() *AttendAppointmentProfessionalOK {

	return &AttendAppointmentProfessionalOK{}
}

// WriteResponse to the client
func (o *AttendAppointmentProfessionalOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AttendAppointmentProfessionalInternalServerErrorCode is the HTTP code returned for type AttendAppointmentProfessionalInternalServerError
const AttendAppointmentProfessionalInternalServerErrorCode int = 500

/*AttendAppointmentProfessionalInternalServerError internal server error

swagger:response attendAppointmentProfessionalInternalServerError
*/
type AttendAppointmentProfessionalInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAttendAppointmentProfessionalInternalServerError creates AttendAppointmentProfessionalInternalServerError with default headers values
func NewAttendAppointmentProfessionalInternalServerError() *AttendAppointmentProfessionalInternalServerError {

	return &AttendAppointmentProfessionalInternalServerError{}
}

// WithPayload adds the payload to the attend appointment professional internal server error response
func (o *AttendAppointmentProfessionalInternalServerError) WithPayload(payload *models.Error) *AttendAppointmentProfessionalInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the attend appointment professional internal server error response
func (o *AttendAppointmentProfessionalInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AttendAppointmentProfessionalInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
