// Code generated by go-swagger; DO NOT EDIT.

package professionals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// GetAppointmentsByprofessionalOKCode is the HTTP code returned for type GetAppointmentsByprofessionalOK
const GetAppointmentsByprofessionalOKCode int = 200

/*GetAppointmentsByprofessionalOK result search appointment professional

swagger:response getAppointmentsByprofessionalOK
*/
type GetAppointmentsByprofessionalOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Appointment `json:"body,omitempty"`
}

// NewGetAppointmentsByprofessionalOK creates GetAppointmentsByprofessionalOK with default headers values
func NewGetAppointmentsByprofessionalOK() *GetAppointmentsByprofessionalOK {

	return &GetAppointmentsByprofessionalOK{}
}

// WithPayload adds the payload to the get appointments byprofessional o k response
func (o *GetAppointmentsByprofessionalOK) WithPayload(payload []*models.Appointment) *GetAppointmentsByprofessionalOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get appointments byprofessional o k response
func (o *GetAppointmentsByprofessionalOK) SetPayload(payload []*models.Appointment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppointmentsByprofessionalOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Appointment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAppointmentsByprofessionalInternalServerErrorCode is the HTTP code returned for type GetAppointmentsByprofessionalInternalServerError
const GetAppointmentsByprofessionalInternalServerErrorCode int = 500

/*GetAppointmentsByprofessionalInternalServerError internal server error

swagger:response getAppointmentsByprofessionalInternalServerError
*/
type GetAppointmentsByprofessionalInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAppointmentsByprofessionalInternalServerError creates GetAppointmentsByprofessionalInternalServerError with default headers values
func NewGetAppointmentsByprofessionalInternalServerError() *GetAppointmentsByprofessionalInternalServerError {

	return &GetAppointmentsByprofessionalInternalServerError{}
}

// WithPayload adds the payload to the get appointments byprofessional internal server error response
func (o *GetAppointmentsByprofessionalInternalServerError) WithPayload(payload *models.Error) *GetAppointmentsByprofessionalInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get appointments byprofessional internal server error response
func (o *GetAppointmentsByprofessionalInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppointmentsByprofessionalInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
