// Code generated by go-swagger; DO NOT EDIT.

package professionals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAppointmentByProfessionalAppointmentIDHandlerFunc turns a function with the right signature into a get appointment by professional appointment Id handler
type GetAppointmentByProfessionalAppointmentIDHandlerFunc func(GetAppointmentByProfessionalAppointmentIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppointmentByProfessionalAppointmentIDHandlerFunc) Handle(params GetAppointmentByProfessionalAppointmentIDParams) middleware.Responder {
	return fn(params)
}

// GetAppointmentByProfessionalAppointmentIDHandler interface for that can handle valid get appointment by professional appointment Id params
type GetAppointmentByProfessionalAppointmentIDHandler interface {
	Handle(GetAppointmentByProfessionalAppointmentIDParams) middleware.Responder
}

// NewGetAppointmentByProfessionalAppointmentID creates a new http.Handler for the get appointment by professional appointment Id operation
func NewGetAppointmentByProfessionalAppointmentID(ctx *middleware.Context, handler GetAppointmentByProfessionalAppointmentIDHandler) *GetAppointmentByProfessionalAppointmentID {
	return &GetAppointmentByProfessionalAppointmentID{Context: ctx, Handler: handler}
}

/*GetAppointmentByProfessionalAppointmentID swagger:route GET /v1/professionals/{id}/appointments/{idappointment} professionals getAppointmentByProfessionalAppointmentId

GetAppointmentByProfessionalAppointmentID get appointment by professional appointment Id API

*/
type GetAppointmentByProfessionalAppointmentID struct {
	Context *middleware.Context
	Handler GetAppointmentByProfessionalAppointmentIDHandler
}

func (o *GetAppointmentByProfessionalAppointmentID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAppointmentByProfessionalAppointmentIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
