// Code generated by go-swagger; DO NOT EDIT.

package professionals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// GetAppointmentByProfessionalAppointmentIDOKCode is the HTTP code returned for type GetAppointmentByProfessionalAppointmentIDOK
const GetAppointmentByProfessionalAppointmentIDOKCode int = 200

/*GetAppointmentByProfessionalAppointmentIDOK get appointment for professional

swagger:response getAppointmentByProfessionalAppointmentIdOK
*/
type GetAppointmentByProfessionalAppointmentIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Appointment `json:"body,omitempty"`
}

// NewGetAppointmentByProfessionalAppointmentIDOK creates GetAppointmentByProfessionalAppointmentIDOK with default headers values
func NewGetAppointmentByProfessionalAppointmentIDOK() *GetAppointmentByProfessionalAppointmentIDOK {

	return &GetAppointmentByProfessionalAppointmentIDOK{}
}

// WithPayload adds the payload to the get appointment by professional appointment Id o k response
func (o *GetAppointmentByProfessionalAppointmentIDOK) WithPayload(payload *models.Appointment) *GetAppointmentByProfessionalAppointmentIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get appointment by professional appointment Id o k response
func (o *GetAppointmentByProfessionalAppointmentIDOK) SetPayload(payload *models.Appointment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppointmentByProfessionalAppointmentIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAppointmentByProfessionalAppointmentIDInternalServerErrorCode is the HTTP code returned for type GetAppointmentByProfessionalAppointmentIDInternalServerError
const GetAppointmentByProfessionalAppointmentIDInternalServerErrorCode int = 500

/*GetAppointmentByProfessionalAppointmentIDInternalServerError internal server error

swagger:response getAppointmentByProfessionalAppointmentIdInternalServerError
*/
type GetAppointmentByProfessionalAppointmentIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAppointmentByProfessionalAppointmentIDInternalServerError creates GetAppointmentByProfessionalAppointmentIDInternalServerError with default headers values
func NewGetAppointmentByProfessionalAppointmentIDInternalServerError() *GetAppointmentByProfessionalAppointmentIDInternalServerError {

	return &GetAppointmentByProfessionalAppointmentIDInternalServerError{}
}

// WithPayload adds the payload to the get appointment by professional appointment Id internal server error response
func (o *GetAppointmentByProfessionalAppointmentIDInternalServerError) WithPayload(payload *models.Error) *GetAppointmentByProfessionalAppointmentIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get appointment by professional appointment Id internal server error response
func (o *GetAppointmentByProfessionalAppointmentIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppointmentByProfessionalAppointmentIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
