// Code generated by go-swagger; DO NOT EDIT.

package specialties

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// SearchSpecialtyOKCode is the HTTP code returned for type SearchSpecialtyOK
const SearchSpecialtyOKCode int = 200

/*SearchSpecialtyOK result search specialties

swagger:response searchSpecialtyOK
*/
type SearchSpecialtyOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Specialty `json:"body,omitempty"`
}

// NewSearchSpecialtyOK creates SearchSpecialtyOK with default headers values
func NewSearchSpecialtyOK() *SearchSpecialtyOK {

	return &SearchSpecialtyOK{}
}

// WithPayload adds the payload to the search specialty o k response
func (o *SearchSpecialtyOK) WithPayload(payload []*models.Specialty) *SearchSpecialtyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search specialty o k response
func (o *SearchSpecialtyOK) SetPayload(payload []*models.Specialty) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchSpecialtyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Specialty, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// SearchSpecialtyInternalServerErrorCode is the HTTP code returned for type SearchSpecialtyInternalServerError
const SearchSpecialtyInternalServerErrorCode int = 500

/*SearchSpecialtyInternalServerError internal server error

swagger:response searchSpecialtyInternalServerError
*/
type SearchSpecialtyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSearchSpecialtyInternalServerError creates SearchSpecialtyInternalServerError with default headers values
func NewSearchSpecialtyInternalServerError() *SearchSpecialtyInternalServerError {

	return &SearchSpecialtyInternalServerError{}
}

// WithPayload adds the payload to the search specialty internal server error response
func (o *SearchSpecialtyInternalServerError) WithPayload(payload *models.Error) *SearchSpecialtyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search specialty internal server error response
func (o *SearchSpecialtyInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchSpecialtyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
