// Code generated by go-swagger; DO NOT EDIT.

package specialties

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SearchSpecialtyHandlerFunc turns a function with the right signature into a search specialty handler
type SearchSpecialtyHandlerFunc func(SearchSpecialtyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchSpecialtyHandlerFunc) Handle(params SearchSpecialtyParams) middleware.Responder {
	return fn(params)
}

// SearchSpecialtyHandler interface for that can handle valid search specialty params
type SearchSpecialtyHandler interface {
	Handle(SearchSpecialtyParams) middleware.Responder
}

// NewSearchSpecialty creates a new http.Handler for the search specialty operation
func NewSearchSpecialty(ctx *middleware.Context, handler SearchSpecialtyHandler) *SearchSpecialty {
	return &SearchSpecialty{Context: ctx, Handler: handler}
}

/*SearchSpecialty swagger:route GET /v1/specialties specialties searchSpecialty

SearchSpecialty search specialty API

*/
type SearchSpecialty struct {
	Context *middleware.Context
	Handler SearchSpecialtyHandler
}

func (o *SearchSpecialty) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSearchSpecialtyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
