version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: prueba12345
      MYSQL_DATABASE: appointment
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
