version: '3'

services:
  db_appointment:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prueba12345
      MYSQL_DATABASE: appointment
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
