version: '3'

services:
  db_appointment:
    image: mysql
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: prueba12345
      MYSQL_DATABASE: appointment
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
 
  appointment:
    restart: always
    ports:
      - "8080:8080"
    image: appointment
    networks:
      - backend 
    environment:
      DBUSER: root
      DBNAME: appointment
      DBPASSWORD: prueba12345
      DBHOST: db_appointment
      DBPORT: 3306
      SMTP_PASSWORD: M28+CMq218ACK2+X>A
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: tpuade.healthycalendar@gmail.com
    depends_on:
      - db_appointment

networks:
  backend:
    driver: "bridge"
