// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi APPointment Backend
API to TPO UADE (Aplicaciones Distribuidas)


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: v1
    Contact: calisi.lucas<calisi.lucas@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
