// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API to TPO UADE (Aplicaciones Distribuidas)",
    "title": "APPointment Backend",
    "contact": {
      "name": "calisi.lucas",
      "email": "calisi.lucas@gmail.com"
    },
    "version": "v1"
  },
  "paths": {
    "/v1/appointments": {
      "get": {
        "tags": [
          "appointments"
        ],
        "operationId": "searchAppointment",
        "parameters": [
          {
            "type": "integer",
            "description": "id of the patient",
            "name": "idPatient",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "id of the professional",
            "name": "idProfessional",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date",
            "description": "start date for appointment",
            "name": "startDate",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date",
            "description": "finish date for appointment",
            "name": "startFinish",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "id for specialty",
            "name": "idspecialty",
            "in": "query"
          },
          {
            "enum": [
              "confirmed",
              "cancelled",
              "pending",
              "avaiable"
            ],
            "type": "string",
            "default": "avaiable",
            "description": "appointment status",
            "name": "status",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "result search appointments",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/login": {
      "post": {
        "tags": [
          "login"
        ],
        "operationId": "login",
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "user",
                "password"
              ],
              "properties": {
                "password": {
                  "type": "string",
                  "format": "password"
                },
                "user": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login successful"
          },
          "401": {
            "description": "access denied"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/patients/{id}": {
      "get": {
        "tags": [
          "patients"
        ],
        "operationId": "getPatientbyId",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id patient",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "result get patient",
            "schema": {
              "$ref": "#/definitions/patient"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/patients/{id}/appointments": {
      "get": {
        "tags": [
          "patients"
        ],
        "operationId": "getAppointmentsByPatient",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id patient",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "appoints for a patient",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/patients/{id}/appointments/{idAppointment}/cancel": {
      "post": {
        "tags": [
          "patients"
        ],
        "operationId": "cancelAppoinmentForPatient",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id patient",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "confirm appoinment",
            "name": "idAppointment",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "appoint for a patient",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/patients/{id}/appointments/{idAppointment}/confirm": {
      "post": {
        "tags": [
          "patients"
        ],
        "operationId": "confirmAppointmentForPatient",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id patient",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "confirm appoinment",
            "name": "idAppointment",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "appoint for a patient",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getProfessionalbyId",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "result professional",
            "schema": {
              "$ref": "#/definitions/professional"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/appointments": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getAppointmentsByprofessional",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "result search appointment professional",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/appointments/{idappointment}": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getAppointmentByProfessionalAppointmentId",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "id appointment",
            "name": "idappointment",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get appointment for professional",
            "schema": {
              "$ref": "#/definitions/appointment"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/appointments/{idappointment}/cancel": {
      "post": {
        "tags": [
          "professionals"
        ],
        "operationId": "cancelAppointmentProfessional",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "id appointment",
            "name": "idappointment",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get appointment for professional"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/specialties": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getSpecialtiesByProfessional",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "resultado specialties professional",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/specialty"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/specialties/{idSpecialty}/schedule": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getProfesionalScheduleBySpecialty",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "id specialty",
            "name": "idSpecialty",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "resultado schedule professional by specialty",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/schedule"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "professionals"
        ],
        "operationId": "setProfesionalScheduleBySpecialty",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "id specialty",
            "name": "idSpecialty",
            "in": "path",
            "required": true
          },
          {
            "name": "schedule",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/schedule"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "resultado schedule professional by specialty",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/schedule"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/specialties": {
      "get": {
        "tags": [
          "specialties"
        ],
        "operationId": "searchSpecialty",
        "parameters": [
          {
            "type": "string",
            "default": "",
            "description": "main category",
            "name": "category",
            "in": "query"
          },
          {
            "type": "string",
            "default": "",
            "description": "secundary category",
            "name": "subCategory",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "result search specialties",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/specialty"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/users/{id}/role": {
      "get": {
        "tags": [
          "users"
        ],
        "operationId": "getRoleOfUser",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id user",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get user role",
            "schema": {
              "$ref": "#/definitions/role"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "appointment": {
      "type": "object",
      "required": [
        "date",
        "status"
      ],
      "properties": {
        "date": {
          "type": "string",
          "format": "date"
        },
        "id": {
          "type": "integer"
        },
        "patient": {
          "$ref": "#/definitions/patient"
        },
        "professional": {
          "$ref": "#/definitions/professional"
        },
        "status": {
          "$ref": "#/definitions/appointmentStatus"
        }
      }
    },
    "appointmentStatus": {
      "type": "string",
      "enum": [
        "confirmed",
        "cancelled",
        "pending",
        "avaiable"
      ]
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int",
          "readOnly": true
        },
        "description": {
          "type": "string",
          "readOnly": true
        },
        "type": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "patient": {
      "type": "object",
      "required": [
        "name",
        "dni",
        "sex",
        "birthDay"
      ],
      "properties": {
        "birthDay": {
          "type": "string",
          "format": "date"
        },
        "dni": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "sex": {
          "type": "string",
          "enum": [
            "masculino",
            "femenino"
          ]
        },
        "userName": {
          "type": "string"
        }
      }
    },
    "professional": {
      "type": "object",
      "required": [
        "name",
        "dni",
        "doctorNumber",
        "birthDay"
      ],
      "properties": {
        "birthDay": {
          "type": "string",
          "format": "date"
        },
        "dni": {
          "type": "integer"
        },
        "doctorNumber": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "userName": {
          "type": "string"
        }
      }
    },
    "role": {
      "type": "object",
      "required": [
        "name",
        "description"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "schedule": {
      "type": "object",
      "required": [
        "year",
        "month",
        "schedule"
      ],
      "properties": {
        "id": {
          "type": "integer"
        },
        "month": {
          "type": "integer"
        },
        "schedule": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "day": {
                "type": "integer"
              },
              "finishTime": {
                "type": "integer",
                "default": 18
              },
              "startTime": {
                "type": "integer",
                "default": 9
              }
            }
          }
        },
        "year": {
          "type": "integer"
        }
      }
    },
    "specialty": {
      "type": "object",
      "required": [
        "category"
      ],
      "properties": {
        "category": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "subCategory": {
          "type": "string"
        }
      }
    },
    "user": {
      "type": "object",
      "required": [
        "id",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "id": {
          "type": "string"
        },
        "lastPasswordChange": {
          "type": "string",
          "format": "date"
        },
        "password": {
          "type": "string",
          "format": "password"
        },
        "status": {
          "$ref": "#/definitions/userStatus"
        },
        "whenCreated": {
          "type": "string",
          "format": "date"
        }
      }
    },
    "userRequestBody": {
      "type": "object",
      "required": [
        "userData"
      ],
      "properties": {
        "patientData": {
          "$ref": "#/definitions/patient"
        },
        "professionalData": {
          "$ref": "#/definitions/professional"
        },
        "userData": {
          "$ref": "#/definitions/user"
        }
      }
    },
    "userStatus": {
      "type": "string",
      "default": "pending",
      "enum": [
        "enabled",
        "disabled",
        "locked",
        "pending"
      ]
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API to TPO UADE (Aplicaciones Distribuidas)",
    "title": "APPointment Backend",
    "contact": {
      "name": "calisi.lucas",
      "email": "calisi.lucas@gmail.com"
    },
    "version": "v1"
  },
  "paths": {
    "/v1/appointments": {
      "get": {
        "tags": [
          "appointments"
        ],
        "operationId": "searchAppointment",
        "parameters": [
          {
            "type": "integer",
            "description": "id of the patient",
            "name": "idPatient",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "id of the professional",
            "name": "idProfessional",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date",
            "description": "start date for appointment",
            "name": "startDate",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date",
            "description": "finish date for appointment",
            "name": "startFinish",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "id for specialty",
            "name": "idspecialty",
            "in": "query"
          },
          {
            "enum": [
              "confirmed",
              "cancelled",
              "pending",
              "avaiable"
            ],
            "type": "string",
            "default": "avaiable",
            "description": "appointment status",
            "name": "status",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "result search appointments",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/login": {
      "post": {
        "tags": [
          "login"
        ],
        "operationId": "login",
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "user",
                "password"
              ],
              "properties": {
                "password": {
                  "type": "string",
                  "format": "password"
                },
                "user": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login successful"
          },
          "401": {
            "description": "access denied"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/patients/{id}": {
      "get": {
        "tags": [
          "patients"
        ],
        "operationId": "getPatientbyId",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id patient",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "result get patient",
            "schema": {
              "$ref": "#/definitions/patient"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/patients/{id}/appointments": {
      "get": {
        "tags": [
          "patients"
        ],
        "operationId": "getAppointmentsByPatient",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id patient",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "appoints for a patient",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/patients/{id}/appointments/{idAppointment}/cancel": {
      "post": {
        "tags": [
          "patients"
        ],
        "operationId": "cancelAppoinmentForPatient",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id patient",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "confirm appoinment",
            "name": "idAppointment",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "appoint for a patient",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/patients/{id}/appointments/{idAppointment}/confirm": {
      "post": {
        "tags": [
          "patients"
        ],
        "operationId": "confirmAppointmentForPatient",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id patient",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "confirm appoinment",
            "name": "idAppointment",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "appoint for a patient",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getProfessionalbyId",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "result professional",
            "schema": {
              "$ref": "#/definitions/professional"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/appointments": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getAppointmentsByprofessional",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "result search appointment professional",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/appointment"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/appointments/{idappointment}": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getAppointmentByProfessionalAppointmentId",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "id appointment",
            "name": "idappointment",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get appointment for professional",
            "schema": {
              "$ref": "#/definitions/appointment"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/appointments/{idappointment}/cancel": {
      "post": {
        "tags": [
          "professionals"
        ],
        "operationId": "cancelAppointmentProfessional",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "id appointment",
            "name": "idappointment",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get appointment for professional"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/specialties": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getSpecialtiesByProfessional",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "resultado specialties professional",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/specialty"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/professionals/{id}/specialties/{idSpecialty}/schedule": {
      "get": {
        "tags": [
          "professionals"
        ],
        "operationId": "getProfesionalScheduleBySpecialty",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "id specialty",
            "name": "idSpecialty",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "resultado schedule professional by specialty",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/schedule"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "professionals"
        ],
        "operationId": "setProfesionalScheduleBySpecialty",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id professional",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "id specialty",
            "name": "idSpecialty",
            "in": "path",
            "required": true
          },
          {
            "name": "schedule",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/schedule"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "resultado schedule professional by specialty",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/schedule"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/specialties": {
      "get": {
        "tags": [
          "specialties"
        ],
        "operationId": "searchSpecialty",
        "parameters": [
          {
            "type": "string",
            "default": "",
            "description": "main category",
            "name": "category",
            "in": "query"
          },
          {
            "type": "string",
            "default": "",
            "description": "secundary category",
            "name": "subCategory",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "result search specialties",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/specialty"
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/v1/users/{id}/role": {
      "get": {
        "tags": [
          "users"
        ],
        "operationId": "getRoleOfUser",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "id user",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get user role",
            "schema": {
              "$ref": "#/definitions/role"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "appointment": {
      "type": "object",
      "required": [
        "date",
        "status"
      ],
      "properties": {
        "date": {
          "type": "string",
          "format": "date"
        },
        "id": {
          "type": "integer"
        },
        "patient": {
          "$ref": "#/definitions/patient"
        },
        "professional": {
          "$ref": "#/definitions/professional"
        },
        "status": {
          "$ref": "#/definitions/appointmentStatus"
        }
      }
    },
    "appointmentStatus": {
      "type": "string",
      "enum": [
        "confirmed",
        "cancelled",
        "pending",
        "avaiable"
      ]
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int",
          "readOnly": true
        },
        "description": {
          "type": "string",
          "readOnly": true
        },
        "type": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "patient": {
      "type": "object",
      "required": [
        "name",
        "dni",
        "sex",
        "birthDay"
      ],
      "properties": {
        "birthDay": {
          "type": "string",
          "format": "date"
        },
        "dni": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "sex": {
          "type": "string",
          "enum": [
            "masculino",
            "femenino"
          ]
        },
        "userName": {
          "type": "string"
        }
      }
    },
    "professional": {
      "type": "object",
      "required": [
        "name",
        "dni",
        "doctorNumber",
        "birthDay"
      ],
      "properties": {
        "birthDay": {
          "type": "string",
          "format": "date"
        },
        "dni": {
          "type": "integer"
        },
        "doctorNumber": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "userName": {
          "type": "string"
        }
      }
    },
    "role": {
      "type": "object",
      "required": [
        "name",
        "description"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "schedule": {
      "type": "object",
      "required": [
        "year",
        "month",
        "schedule"
      ],
      "properties": {
        "id": {
          "type": "integer"
        },
        "month": {
          "type": "integer"
        },
        "schedule": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "day": {
                "type": "integer"
              },
              "finishTime": {
                "type": "integer",
                "default": 18
              },
              "startTime": {
                "type": "integer",
                "default": 9
              }
            }
          }
        },
        "year": {
          "type": "integer"
        }
      }
    },
    "specialty": {
      "type": "object",
      "required": [
        "category"
      ],
      "properties": {
        "category": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "subCategory": {
          "type": "string"
        }
      }
    },
    "user": {
      "type": "object",
      "required": [
        "id",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "id": {
          "type": "string"
        },
        "lastPasswordChange": {
          "type": "string",
          "format": "date"
        },
        "password": {
          "type": "string",
          "format": "password"
        },
        "status": {
          "$ref": "#/definitions/userStatus"
        },
        "whenCreated": {
          "type": "string",
          "format": "date"
        }
      }
    },
    "userRequestBody": {
      "type": "object",
      "required": [
        "userData"
      ],
      "properties": {
        "patientData": {
          "$ref": "#/definitions/patient"
        },
        "professionalData": {
          "$ref": "#/definitions/professional"
        },
        "userData": {
          "$ref": "#/definitions/user"
        }
      }
    },
    "userStatus": {
      "type": "string",
      "default": "pending",
      "enum": [
        "enabled",
        "disabled",
        "locked",
        "pending"
      ]
    }
  }
}`))
}
