// Code generated by go-swagger; DO NOT EDIT.

package appointments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/appointment/http/models"
)

// SearchAppointmentReader is a Reader for the SearchAppointment structure.
type SearchAppointmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchAppointmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchAppointmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewSearchAppointmentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchAppointmentOK creates a SearchAppointmentOK with default headers values
func NewSearchAppointmentOK() *SearchAppointmentOK {
	return &SearchAppointmentOK{}
}

/*SearchAppointmentOK handles this case with default header values.

result search appointments
*/
type SearchAppointmentOK struct {
	Payload []*models.Appointment
}

func (o *SearchAppointmentOK) Error() string {
	return fmt.Sprintf("[GET /v1/appointments][%d] searchAppointmentOK  %+v", 200, o.Payload)
}

func (o *SearchAppointmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAppointmentInternalServerError creates a SearchAppointmentInternalServerError with default headers values
func NewSearchAppointmentInternalServerError() *SearchAppointmentInternalServerError {
	return &SearchAppointmentInternalServerError{}
}

/*SearchAppointmentInternalServerError handles this case with default header values.

internal server error
*/
type SearchAppointmentInternalServerError struct {
	Payload *models.Error
}

func (o *SearchAppointmentInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/appointments][%d] searchAppointmentInternalServerError  %+v", 500, o.Payload)
}

func (o *SearchAppointmentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
