// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCancelAppoinmentForPatientParams creates a new CancelAppoinmentForPatientParams object
// with the default values initialized.
func NewCancelAppoinmentForPatientParams() *CancelAppoinmentForPatientParams {
	var ()
	return &CancelAppoinmentForPatientParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelAppoinmentForPatientParamsWithTimeout creates a new CancelAppoinmentForPatientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelAppoinmentForPatientParamsWithTimeout(timeout time.Duration) *CancelAppoinmentForPatientParams {
	var ()
	return &CancelAppoinmentForPatientParams{

		timeout: timeout,
	}
}

// NewCancelAppoinmentForPatientParamsWithContext creates a new CancelAppoinmentForPatientParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelAppoinmentForPatientParamsWithContext(ctx context.Context) *CancelAppoinmentForPatientParams {
	var ()
	return &CancelAppoinmentForPatientParams{

		Context: ctx,
	}
}

// NewCancelAppoinmentForPatientParamsWithHTTPClient creates a new CancelAppoinmentForPatientParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCancelAppoinmentForPatientParamsWithHTTPClient(client *http.Client) *CancelAppoinmentForPatientParams {
	var ()
	return &CancelAppoinmentForPatientParams{
		HTTPClient: client,
	}
}

/*CancelAppoinmentForPatientParams contains all the parameters to send to the API endpoint
for the cancel appoinment for patient operation typically these are written to a http.Request
*/
type CancelAppoinmentForPatientParams struct {

	/*ID
	  id patient

	*/
	ID int64
	/*IDAppointment
	  confirm appoinment

	*/
	IDAppointment int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) WithTimeout(timeout time.Duration) *CancelAppoinmentForPatientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) WithContext(ctx context.Context) *CancelAppoinmentForPatientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) WithHTTPClient(client *http.Client) *CancelAppoinmentForPatientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) WithID(id int64) *CancelAppoinmentForPatientParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) SetID(id int64) {
	o.ID = id
}

// WithIDAppointment adds the iDAppointment to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) WithIDAppointment(iDAppointment int64) *CancelAppoinmentForPatientParams {
	o.SetIDAppointment(iDAppointment)
	return o
}

// SetIDAppointment adds the idAppointment to the cancel appoinment for patient params
func (o *CancelAppoinmentForPatientParams) SetIDAppointment(iDAppointment int64) {
	o.IDAppointment = iDAppointment
}

// WriteToRequest writes these params to a swagger request
func (o *CancelAppoinmentForPatientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param idAppointment
	if err := r.SetPathParam("idAppointment", swag.FormatInt64(o.IDAppointment)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
