// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/appointment/http/models"
)

// CancelAppoinmentForPatientReader is a Reader for the CancelAppoinmentForPatient structure.
type CancelAppoinmentForPatientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CancelAppoinmentForPatientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCancelAppoinmentForPatientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewCancelAppoinmentForPatientInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCancelAppoinmentForPatientOK creates a CancelAppoinmentForPatientOK with default headers values
func NewCancelAppoinmentForPatientOK() *CancelAppoinmentForPatientOK {
	return &CancelAppoinmentForPatientOK{}
}

/*CancelAppoinmentForPatientOK handles this case with default header values.

appoint for a patient
*/
type CancelAppoinmentForPatientOK struct {
}

func (o *CancelAppoinmentForPatientOK) Error() string {
	return fmt.Sprintf("[PUT /v1/patients/{id}/appointments/{idAppointment}/cancel][%d] cancelAppoinmentForPatientOK ", 200)
}

func (o *CancelAppoinmentForPatientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCancelAppoinmentForPatientInternalServerError creates a CancelAppoinmentForPatientInternalServerError with default headers values
func NewCancelAppoinmentForPatientInternalServerError() *CancelAppoinmentForPatientInternalServerError {
	return &CancelAppoinmentForPatientInternalServerError{}
}

/*CancelAppoinmentForPatientInternalServerError handles this case with default header values.

internal server error
*/
type CancelAppoinmentForPatientInternalServerError struct {
	Payload *models.Error
}

func (o *CancelAppoinmentForPatientInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/patients/{id}/appointments/{idAppointment}/cancel][%d] cancelAppoinmentForPatientInternalServerError  %+v", 500, o.Payload)
}

func (o *CancelAppoinmentForPatientInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
