// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/appointment/http/models"
)

// ConfirmAppointmentForPatientReader is a Reader for the ConfirmAppointmentForPatient structure.
type ConfirmAppointmentForPatientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConfirmAppointmentForPatientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewConfirmAppointmentForPatientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewConfirmAppointmentForPatientInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewConfirmAppointmentForPatientOK creates a ConfirmAppointmentForPatientOK with default headers values
func NewConfirmAppointmentForPatientOK() *ConfirmAppointmentForPatientOK {
	return &ConfirmAppointmentForPatientOK{}
}

/*ConfirmAppointmentForPatientOK handles this case with default header values.

appoint for a patient
*/
type ConfirmAppointmentForPatientOK struct {
	Payload []*models.Appointment
}

func (o *ConfirmAppointmentForPatientOK) Error() string {
	return fmt.Sprintf("[PUT /v1/patients/{id}/appointments/{idAppointment}/confirm][%d] confirmAppointmentForPatientOK  %+v", 200, o.Payload)
}

func (o *ConfirmAppointmentForPatientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfirmAppointmentForPatientInternalServerError creates a ConfirmAppointmentForPatientInternalServerError with default headers values
func NewConfirmAppointmentForPatientInternalServerError() *ConfirmAppointmentForPatientInternalServerError {
	return &ConfirmAppointmentForPatientInternalServerError{}
}

/*ConfirmAppointmentForPatientInternalServerError handles this case with default header values.

internal server error
*/
type ConfirmAppointmentForPatientInternalServerError struct {
	Payload *models.Error
}

func (o *ConfirmAppointmentForPatientInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/patients/{id}/appointments/{idAppointment}/confirm][%d] confirmAppointmentForPatientInternalServerError  %+v", 500, o.Payload)
}

func (o *ConfirmAppointmentForPatientInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
