// Code generated by go-swagger; DO NOT EDIT.

package patients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/appointment/http/models"
)

// RequestAppointmentForPatientReader is a Reader for the RequestAppointmentForPatient structure.
type RequestAppointmentForPatientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestAppointmentForPatientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRequestAppointmentForPatientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewRequestAppointmentForPatientInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRequestAppointmentForPatientOK creates a RequestAppointmentForPatientOK with default headers values
func NewRequestAppointmentForPatientOK() *RequestAppointmentForPatientOK {
	return &RequestAppointmentForPatientOK{}
}

/*RequestAppointmentForPatientOK handles this case with default header values.

appoint for a patient
*/
type RequestAppointmentForPatientOK struct {
	Payload []*models.Appointment
}

func (o *RequestAppointmentForPatientOK) Error() string {
	return fmt.Sprintf("[PUT /v1/patients/{id}/appointments/{idAppointment}/request][%d] requestAppointmentForPatientOK  %+v", 200, o.Payload)
}

func (o *RequestAppointmentForPatientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRequestAppointmentForPatientInternalServerError creates a RequestAppointmentForPatientInternalServerError with default headers values
func NewRequestAppointmentForPatientInternalServerError() *RequestAppointmentForPatientInternalServerError {
	return &RequestAppointmentForPatientInternalServerError{}
}

/*RequestAppointmentForPatientInternalServerError handles this case with default header values.

internal server error
*/
type RequestAppointmentForPatientInternalServerError struct {
	Payload *models.Error
}

func (o *RequestAppointmentForPatientInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/patients/{id}/appointments/{idAppointment}/request][%d] requestAppointmentForPatientInternalServerError  %+v", 500, o.Payload)
}

func (o *RequestAppointmentForPatientInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
