// Code generated by go-swagger; DO NOT EDIT.

package queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddPatientToQueueHandlerFunc turns a function with the right signature into a add patient to queue handler
type AddPatientToQueueHandlerFunc func(AddPatientToQueueParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddPatientToQueueHandlerFunc) Handle(params AddPatientToQueueParams) middleware.Responder {
	return fn(params)
}

// AddPatientToQueueHandler interface for that can handle valid add patient to queue params
type AddPatientToQueueHandler interface {
	Handle(AddPatientToQueueParams) middleware.Responder
}

// NewAddPatientToQueue creates a new http.Handler for the add patient to queue operation
func NewAddPatientToQueue(ctx *middleware.Context, handler AddPatientToQueueHandler) *AddPatientToQueue {
	return &AddPatientToQueue{Context: ctx, Handler: handler}
}

/*AddPatientToQueue swagger:route POST /v1/queue queue addPatientToQueue

AddPatientToQueue add patient to queue API

*/
type AddPatientToQueue struct {
	Context *middleware.Context
	Handler AddPatientToQueueHandler
}

func (o *AddPatientToQueue) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddPatientToQueueParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
