// Code generated by go-swagger; DO NOT EDIT.

package queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/appointment/http/models"
)

// NewAddPatientToQueueParams creates a new AddPatientToQueueParams object
// no default values defined in spec.
func NewAddPatientToQueueParams() AddPatientToQueueParams {

	return AddPatientToQueueParams{}
}

// AddPatientToQueueParams contains all the bound params for the add patient to queue operation
// typically these are obtained from a http.Request
//
// swagger:parameters addPatientToQueue
type AddPatientToQueueParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Item *models.QueueItem
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddPatientToQueueParams() beforehand.
func (o *AddPatientToQueueParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.QueueItem
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("item", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Item = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
