// Code generated by go-swagger; DO NOT EDIT.

package queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetQueueHandlerFunc turns a function with the right signature into a get queue handler
type GetQueueHandlerFunc func(GetQueueParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetQueueHandlerFunc) Handle(params GetQueueParams) middleware.Responder {
	return fn(params)
}

// GetQueueHandler interface for that can handle valid get queue params
type GetQueueHandler interface {
	Handle(GetQueueParams) middleware.Responder
}

// NewGetQueue creates a new http.Handler for the get queue operation
func NewGetQueue(ctx *middleware.Context, handler GetQueueHandler) *GetQueue {
	return &GetQueue{Context: ctx, Handler: handler}
}

/*GetQueue swagger:route GET /v1/queue queue getQueue

GetQueue get queue API

*/
type GetQueue struct {
	Context *middleware.Context
	Handler GetQueueHandler
}

func (o *GetQueue) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetQueueParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
