// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/appointment/http/models"
)

// GetRoleOfUserReader is a Reader for the GetRoleOfUser structure.
type GetRoleOfUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoleOfUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRoleOfUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetRoleOfUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRoleOfUserOK creates a GetRoleOfUserOK with default headers values
func NewGetRoleOfUserOK() *GetRoleOfUserOK {
	return &GetRoleOfUserOK{}
}

/*GetRoleOfUserOK handles this case with default header values.

get user role
*/
type GetRoleOfUserOK struct {
	Payload *models.Role
}

func (o *GetRoleOfUserOK) Error() string {
	return fmt.Sprintf("[GET /v1/users/{id}/role][%d] getRoleOfUserOK  %+v", 200, o.Payload)
}

func (o *GetRoleOfUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Role)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoleOfUserInternalServerError creates a GetRoleOfUserInternalServerError with default headers values
func NewGetRoleOfUserInternalServerError() *GetRoleOfUserInternalServerError {
	return &GetRoleOfUserInternalServerError{}
}

/*GetRoleOfUserInternalServerError handles this case with default header values.

internal server error
*/
type GetRoleOfUserInternalServerError struct {
	Payload *models.Error
}

func (o *GetRoleOfUserInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/users/{id}/role][%d] getRoleOfUserInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRoleOfUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
