// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRoleOfUserParams creates a new GetRoleOfUserParams object
// with the default values initialized.
func NewGetRoleOfUserParams() *GetRoleOfUserParams {
	var ()
	return &GetRoleOfUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoleOfUserParamsWithTimeout creates a new GetRoleOfUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRoleOfUserParamsWithTimeout(timeout time.Duration) *GetRoleOfUserParams {
	var ()
	return &GetRoleOfUserParams{

		timeout: timeout,
	}
}

// NewGetRoleOfUserParamsWithContext creates a new GetRoleOfUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRoleOfUserParamsWithContext(ctx context.Context) *GetRoleOfUserParams {
	var ()
	return &GetRoleOfUserParams{

		Context: ctx,
	}
}

// NewGetRoleOfUserParamsWithHTTPClient creates a new GetRoleOfUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRoleOfUserParamsWithHTTPClient(client *http.Client) *GetRoleOfUserParams {
	var ()
	return &GetRoleOfUserParams{
		HTTPClient: client,
	}
}

/*GetRoleOfUserParams contains all the parameters to send to the API endpoint
for the get role of user operation typically these are written to a http.Request
*/
type GetRoleOfUserParams struct {

	/*ID
	  id user

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get role of user params
func (o *GetRoleOfUserParams) WithTimeout(timeout time.Duration) *GetRoleOfUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get role of user params
func (o *GetRoleOfUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get role of user params
func (o *GetRoleOfUserParams) WithContext(ctx context.Context) *GetRoleOfUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get role of user params
func (o *GetRoleOfUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get role of user params
func (o *GetRoleOfUserParams) WithHTTPClient(client *http.Client) *GetRoleOfUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get role of user params
func (o *GetRoleOfUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get role of user params
func (o *GetRoleOfUserParams) WithID(id int64) *GetRoleOfUserParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get role of user params
func (o *GetRoleOfUserParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoleOfUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
