// Code generated by go-swagger; DO NOT EDIT.

package appointments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchAppointmentParams creates a new SearchAppointmentParams object
// with the default values initialized.
func NewSearchAppointmentParams() SearchAppointmentParams {

	var (
		// initialize parameters with default values

		statusDefault = string("avaiable")
	)

	return SearchAppointmentParams{
		Status: &statusDefault,
	}
}

// SearchAppointmentParams contains all the bound params for the search appointment operation
// typically these are obtained from a http.Request
//
// swagger:parameters searchAppointment
type SearchAppointmentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*id of the patient
	  In: query
	*/
	IDPatient *int64
	/*id of the professional
	  In: query
	*/
	IDProfessional *int64
	/*id for specialty
	  In: query
	*/
	Idspecialty *int64
	/*start date for appointment
	  In: query
	*/
	StartDate *strfmt.Date
	/*finish date for appointment
	  In: query
	*/
	StartFinish *strfmt.Date
	/*appointment status
	  In: query
	  Default: "avaiable"
	*/
	Status *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSearchAppointmentParams() beforehand.
func (o *SearchAppointmentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qIDPatient, qhkIDPatient, _ := qs.GetOK("idPatient")
	if err := o.bindIDPatient(qIDPatient, qhkIDPatient, route.Formats); err != nil {
		res = append(res, err)
	}

	qIDProfessional, qhkIDProfessional, _ := qs.GetOK("idProfessional")
	if err := o.bindIDProfessional(qIDProfessional, qhkIDProfessional, route.Formats); err != nil {
		res = append(res, err)
	}

	qIdspecialty, qhkIdspecialty, _ := qs.GetOK("idspecialty")
	if err := o.bindIdspecialty(qIdspecialty, qhkIdspecialty, route.Formats); err != nil {
		res = append(res, err)
	}

	qStartDate, qhkStartDate, _ := qs.GetOK("startDate")
	if err := o.bindStartDate(qStartDate, qhkStartDate, route.Formats); err != nil {
		res = append(res, err)
	}

	qStartFinish, qhkStartFinish, _ := qs.GetOK("startFinish")
	if err := o.bindStartFinish(qStartFinish, qhkStartFinish, route.Formats); err != nil {
		res = append(res, err)
	}

	qStatus, qhkStatus, _ := qs.GetOK("status")
	if err := o.bindStatus(qStatus, qhkStatus, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIDPatient binds and validates parameter IDPatient from query.
func (o *SearchAppointmentParams) bindIDPatient(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("idPatient", "query", "int64", raw)
	}
	o.IDPatient = &value

	return nil
}

// bindIDProfessional binds and validates parameter IDProfessional from query.
func (o *SearchAppointmentParams) bindIDProfessional(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("idProfessional", "query", "int64", raw)
	}
	o.IDProfessional = &value

	return nil
}

// bindIdspecialty binds and validates parameter Idspecialty from query.
func (o *SearchAppointmentParams) bindIdspecialty(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("idspecialty", "query", "int64", raw)
	}
	o.Idspecialty = &value

	return nil
}

// bindStartDate binds and validates parameter StartDate from query.
func (o *SearchAppointmentParams) bindStartDate(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date
	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("startDate", "query", "strfmt.Date", raw)
	}
	o.StartDate = (value.(*strfmt.Date))

	if err := o.validateStartDate(formats); err != nil {
		return err
	}

	return nil
}

// validateStartDate carries on validations for parameter StartDate
func (o *SearchAppointmentParams) validateStartDate(formats strfmt.Registry) error {

	if err := validate.FormatOf("startDate", "query", "date", o.StartDate.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindStartFinish binds and validates parameter StartFinish from query.
func (o *SearchAppointmentParams) bindStartFinish(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date
	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("startFinish", "query", "strfmt.Date", raw)
	}
	o.StartFinish = (value.(*strfmt.Date))

	if err := o.validateStartFinish(formats); err != nil {
		return err
	}

	return nil
}

// validateStartFinish carries on validations for parameter StartFinish
func (o *SearchAppointmentParams) validateStartFinish(formats strfmt.Registry) error {

	if err := validate.FormatOf("startFinish", "query", "date", o.StartFinish.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindStatus binds and validates parameter Status from query.
func (o *SearchAppointmentParams) bindStatus(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSearchAppointmentParams()
		return nil
	}

	o.Status = &raw

	if err := o.validateStatus(formats); err != nil {
		return err
	}

	return nil
}

// validateStatus carries on validations for parameter Status
func (o *SearchAppointmentParams) validateStatus(formats strfmt.Registry) error {

	if err := validate.Enum("status", "query", *o.Status, []interface{}{"confirmed", "cancelled", "pending", "avaiable"}); err != nil {
		return err
	}

	return nil
}
