// Code generated by go-swagger; DO NOT EDIT.

package appointments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appointment/http/models"
)

// SearchAppointmentOKCode is the HTTP code returned for type SearchAppointmentOK
const SearchAppointmentOKCode int = 200

/*SearchAppointmentOK result search appointments

swagger:response searchAppointmentOK
*/
type SearchAppointmentOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Appointment `json:"body,omitempty"`
}

// NewSearchAppointmentOK creates SearchAppointmentOK with default headers values
func NewSearchAppointmentOK() *SearchAppointmentOK {

	return &SearchAppointmentOK{}
}

// WithPayload adds the payload to the search appointment o k response
func (o *SearchAppointmentOK) WithPayload(payload []*models.Appointment) *SearchAppointmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search appointment o k response
func (o *SearchAppointmentOK) SetPayload(payload []*models.Appointment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchAppointmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Appointment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// SearchAppointmentInternalServerErrorCode is the HTTP code returned for type SearchAppointmentInternalServerError
const SearchAppointmentInternalServerErrorCode int = 500

/*SearchAppointmentInternalServerError internal server error

swagger:response searchAppointmentInternalServerError
*/
type SearchAppointmentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSearchAppointmentInternalServerError creates SearchAppointmentInternalServerError with default headers values
func NewSearchAppointmentInternalServerError() *SearchAppointmentInternalServerError {

	return &SearchAppointmentInternalServerError{}
}

// WithPayload adds the payload to the search appointment internal server error response
func (o *SearchAppointmentInternalServerError) WithPayload(payload *models.Error) *SearchAppointmentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search appointment internal server error response
func (o *SearchAppointmentInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchAppointmentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
