// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// QueueItem queue item
// swagger:model queueItem
type QueueItem struct {

	// id
	ID int64 `json:"id,omitempty"`

	// id patient
	// Required: true
	IDPatient *int64 `json:"idPatient"`

	// id specialty
	// Required: true
	IDSpecialty *int64 `json:"idSpecialty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this queue item
func (m *QueueItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIDPatient(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIDSpecialty(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueueItem) validateIDPatient(formats strfmt.Registry) error {

	if err := validate.Required("idPatient", "body", m.IDPatient); err != nil {
		return err
	}

	return nil
}

func (m *QueueItem) validateIDSpecialty(formats strfmt.Registry) error {

	if err := validate.Required("idSpecialty", "body", m.IDSpecialty); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *QueueItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueueItem) UnmarshalBinary(b []byte) error {
	var res QueueItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
