// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserRequestBody user request body
// swagger:model userRequestBody
type UserRequestBody struct {

	// patient data
	PatientData *Patient `json:"patientData,omitempty"`

	// professional data
	ProfessionalData *Professional `json:"professionalData,omitempty"`

	// user data
	// Required: true
	UserData *User `json:"userData"`
}

// Validate validates this user request body
func (m *UserRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePatientData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfessionalData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserRequestBody) validatePatientData(formats strfmt.Registry) error {

	if swag.IsZero(m.PatientData) { // not required
		return nil
	}

	if m.PatientData != nil {
		if err := m.PatientData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("patientData")
			}
			return err
		}
	}

	return nil
}

func (m *UserRequestBody) validateProfessionalData(formats strfmt.Registry) error {

	if swag.IsZero(m.ProfessionalData) { // not required
		return nil
	}

	if m.ProfessionalData != nil {
		if err := m.ProfessionalData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("professionalData")
			}
			return err
		}
	}

	return nil
}

func (m *UserRequestBody) validateUserData(formats strfmt.Registry) error {

	if err := validate.Required("userData", "body", m.UserData); err != nil {
		return err
	}

	if m.UserData != nil {
		if err := m.UserData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("userData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserRequestBody) UnmarshalBinary(b []byte) error {
	var res UserRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
