// Code generated by go-swagger; DO NOT EDIT.

package professionals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/appointment/http/models"
)

// CancelAppointmentProfessionalReader is a Reader for the CancelAppointmentProfessional structure.
type CancelAppointmentProfessionalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CancelAppointmentProfessionalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCancelAppointmentProfessionalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewCancelAppointmentProfessionalInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCancelAppointmentProfessionalOK creates a CancelAppointmentProfessionalOK with default headers values
func NewCancelAppointmentProfessionalOK() *CancelAppointmentProfessionalOK {
	return &CancelAppointmentProfessionalOK{}
}

/*CancelAppointmentProfessionalOK handles this case with default header values.

get appointment for professional
*/
type CancelAppointmentProfessionalOK struct {
}

func (o *CancelAppointmentProfessionalOK) Error() string {
	return fmt.Sprintf("[PUT /v1/professionals/{id}/appointments/{idappointment}/cancel][%d] cancelAppointmentProfessionalOK ", 200)
}

func (o *CancelAppointmentProfessionalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCancelAppointmentProfessionalInternalServerError creates a CancelAppointmentProfessionalInternalServerError with default headers values
func NewCancelAppointmentProfessionalInternalServerError() *CancelAppointmentProfessionalInternalServerError {
	return &CancelAppointmentProfessionalInternalServerError{}
}

/*CancelAppointmentProfessionalInternalServerError handles this case with default header values.

internal server error
*/
type CancelAppointmentProfessionalInternalServerError struct {
	Payload *models.Error
}

func (o *CancelAppointmentProfessionalInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/professionals/{id}/appointments/{idappointment}/cancel][%d] cancelAppointmentProfessionalInternalServerError  %+v", 500, o.Payload)
}

func (o *CancelAppointmentProfessionalInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
