// Code generated by go-swagger; DO NOT EDIT.

package professionals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCancelAppointmentProfessionalParams creates a new CancelAppointmentProfessionalParams object
// with the default values initialized.
func NewCancelAppointmentProfessionalParams() *CancelAppointmentProfessionalParams {
	var ()
	return &CancelAppointmentProfessionalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelAppointmentProfessionalParamsWithTimeout creates a new CancelAppointmentProfessionalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelAppointmentProfessionalParamsWithTimeout(timeout time.Duration) *CancelAppointmentProfessionalParams {
	var ()
	return &CancelAppointmentProfessionalParams{

		timeout: timeout,
	}
}

// NewCancelAppointmentProfessionalParamsWithContext creates a new CancelAppointmentProfessionalParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelAppointmentProfessionalParamsWithContext(ctx context.Context) *CancelAppointmentProfessionalParams {
	var ()
	return &CancelAppointmentProfessionalParams{

		Context: ctx,
	}
}

// NewCancelAppointmentProfessionalParamsWithHTTPClient creates a new CancelAppointmentProfessionalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCancelAppointmentProfessionalParamsWithHTTPClient(client *http.Client) *CancelAppointmentProfessionalParams {
	var ()
	return &CancelAppointmentProfessionalParams{
		HTTPClient: client,
	}
}

/*CancelAppointmentProfessionalParams contains all the parameters to send to the API endpoint
for the cancel appointment professional operation typically these are written to a http.Request
*/
type CancelAppointmentProfessionalParams struct {

	/*ID
	  id professional

	*/
	ID int64
	/*Idappointment
	  id appointment

	*/
	Idappointment int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) WithTimeout(timeout time.Duration) *CancelAppointmentProfessionalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) WithContext(ctx context.Context) *CancelAppointmentProfessionalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) WithHTTPClient(client *http.Client) *CancelAppointmentProfessionalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) WithID(id int64) *CancelAppointmentProfessionalParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) SetID(id int64) {
	o.ID = id
}

// WithIdappointment adds the idappointment to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) WithIdappointment(idappointment int64) *CancelAppointmentProfessionalParams {
	o.SetIdappointment(idappointment)
	return o
}

// SetIdappointment adds the idappointment to the cancel appointment professional params
func (o *CancelAppointmentProfessionalParams) SetIdappointment(idappointment int64) {
	o.Idappointment = idappointment
}

// WriteToRequest writes these params to a swagger request
func (o *CancelAppointmentProfessionalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param idappointment
	if err := r.SetPathParam("idappointment", swag.FormatInt64(o.Idappointment)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
