// Code generated by go-swagger; DO NOT EDIT.

package professionals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/appointment/http/models"
)

// GetProfesionalScheduleBySpecialtyReader is a Reader for the GetProfesionalScheduleBySpecialty structure.
type GetProfesionalScheduleBySpecialtyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProfesionalScheduleBySpecialtyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProfesionalScheduleBySpecialtyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetProfesionalScheduleBySpecialtyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProfesionalScheduleBySpecialtyOK creates a GetProfesionalScheduleBySpecialtyOK with default headers values
func NewGetProfesionalScheduleBySpecialtyOK() *GetProfesionalScheduleBySpecialtyOK {
	return &GetProfesionalScheduleBySpecialtyOK{}
}

/*GetProfesionalScheduleBySpecialtyOK handles this case with default header values.

resultado schedule professional by specialty
*/
type GetProfesionalScheduleBySpecialtyOK struct {
	Payload []*models.Schedule
}

func (o *GetProfesionalScheduleBySpecialtyOK) Error() string {
	return fmt.Sprintf("[GET /v1/professionals/{id}/specialties/{idSpecialty}/schedule][%d] getProfesionalScheduleBySpecialtyOK  %+v", 200, o.Payload)
}

func (o *GetProfesionalScheduleBySpecialtyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProfesionalScheduleBySpecialtyInternalServerError creates a GetProfesionalScheduleBySpecialtyInternalServerError with default headers values
func NewGetProfesionalScheduleBySpecialtyInternalServerError() *GetProfesionalScheduleBySpecialtyInternalServerError {
	return &GetProfesionalScheduleBySpecialtyInternalServerError{}
}

/*GetProfesionalScheduleBySpecialtyInternalServerError handles this case with default header values.

internal server error
*/
type GetProfesionalScheduleBySpecialtyInternalServerError struct {
	Payload *models.Error
}

func (o *GetProfesionalScheduleBySpecialtyInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/professionals/{id}/specialties/{idSpecialty}/schedule][%d] getProfesionalScheduleBySpecialtyInternalServerError  %+v", 500, o.Payload)
}

func (o *GetProfesionalScheduleBySpecialtyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
