// Code generated by go-swagger; DO NOT EDIT.

package professionals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProfesionalScheduleBySpecialtyParams creates a new GetProfesionalScheduleBySpecialtyParams object
// with the default values initialized.
func NewGetProfesionalScheduleBySpecialtyParams() *GetProfesionalScheduleBySpecialtyParams {
	var ()
	return &GetProfesionalScheduleBySpecialtyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProfesionalScheduleBySpecialtyParamsWithTimeout creates a new GetProfesionalScheduleBySpecialtyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProfesionalScheduleBySpecialtyParamsWithTimeout(timeout time.Duration) *GetProfesionalScheduleBySpecialtyParams {
	var ()
	return &GetProfesionalScheduleBySpecialtyParams{

		timeout: timeout,
	}
}

// NewGetProfesionalScheduleBySpecialtyParamsWithContext creates a new GetProfesionalScheduleBySpecialtyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProfesionalScheduleBySpecialtyParamsWithContext(ctx context.Context) *GetProfesionalScheduleBySpecialtyParams {
	var ()
	return &GetProfesionalScheduleBySpecialtyParams{

		Context: ctx,
	}
}

// NewGetProfesionalScheduleBySpecialtyParamsWithHTTPClient creates a new GetProfesionalScheduleBySpecialtyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProfesionalScheduleBySpecialtyParamsWithHTTPClient(client *http.Client) *GetProfesionalScheduleBySpecialtyParams {
	var ()
	return &GetProfesionalScheduleBySpecialtyParams{
		HTTPClient: client,
	}
}

/*GetProfesionalScheduleBySpecialtyParams contains all the parameters to send to the API endpoint
for the get profesional schedule by specialty operation typically these are written to a http.Request
*/
type GetProfesionalScheduleBySpecialtyParams struct {

	/*ID
	  id professional

	*/
	ID int64
	/*IDSpecialty
	  id specialty

	*/
	IDSpecialty int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) WithTimeout(timeout time.Duration) *GetProfesionalScheduleBySpecialtyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) WithContext(ctx context.Context) *GetProfesionalScheduleBySpecialtyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) WithHTTPClient(client *http.Client) *GetProfesionalScheduleBySpecialtyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) WithID(id int64) *GetProfesionalScheduleBySpecialtyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) SetID(id int64) {
	o.ID = id
}

// WithIDSpecialty adds the iDSpecialty to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) WithIDSpecialty(iDSpecialty int64) *GetProfesionalScheduleBySpecialtyParams {
	o.SetIDSpecialty(iDSpecialty)
	return o
}

// SetIDSpecialty adds the idSpecialty to the get profesional schedule by specialty params
func (o *GetProfesionalScheduleBySpecialtyParams) SetIDSpecialty(iDSpecialty int64) {
	o.IDSpecialty = iDSpecialty
}

// WriteToRequest writes these params to a swagger request
func (o *GetProfesionalScheduleBySpecialtyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param idSpecialty
	if err := r.SetPathParam("idSpecialty", swag.FormatInt64(o.IDSpecialty)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
