// Code generated by go-swagger; DO NOT EDIT.

package queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/appointment/http/models"
)

// GetQueueReader is a Reader for the GetQueue structure.
type GetQueueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQueueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetQueueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetQueueInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetQueueOK creates a GetQueueOK with default headers values
func NewGetQueueOK() *GetQueueOK {
	return &GetQueueOK{}
}

/*GetQueueOK handles this case with default header values.

get successful
*/
type GetQueueOK struct {
	Payload *models.Queue
}

func (o *GetQueueOK) Error() string {
	return fmt.Sprintf("[GET /v1/queue][%d] getQueueOK  %+v", 200, o.Payload)
}

func (o *GetQueueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Queue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetQueueInternalServerError creates a GetQueueInternalServerError with default headers values
func NewGetQueueInternalServerError() *GetQueueInternalServerError {
	return &GetQueueInternalServerError{}
}

/*GetQueueInternalServerError handles this case with default header values.

internal server error
*/
type GetQueueInternalServerError struct {
	Payload *models.Error
}

func (o *GetQueueInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/queue][%d] getQueueInternalServerError  %+v", 500, o.Payload)
}

func (o *GetQueueInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
