// Code generated by go-swagger; DO NOT EDIT.

package queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new queue API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for queue API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetQueue get queue API
*/
func (a *Client) GetQueue(params *GetQueueParams) (*GetQueueOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetQueueParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetQueue",
		Method:             "GET",
		PathPattern:        "/v1/queue",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetQueueReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetQueueOK), nil

}

/*
AddPatientToQueue add patient to queue API
*/
func (a *Client) AddPatientToQueue(params *AddPatientToQueueParams) (*AddPatientToQueueOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddPatientToQueueParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "addPatientToQueue",
		Method:             "POST",
		PathPattern:        "/v1/queue",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AddPatientToQueueReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AddPatientToQueueOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
